// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2l_55xArw8nEmRG0m_9xeD6rviMkGc44',
    appId: '1:322685866747:web:aa42f6d03cbbbbe7c9965e',
    messagingSenderId: '322685866747',
    projectId: 'fluttertest-bee29',
    authDomain: 'fluttertest-bee29.firebaseapp.com',
    storageBucket: 'fluttertest-bee29.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIJbyZgecqf3xI993txfQ4Iaw8uQwHNwA',
    appId: '1:322685866747:android:15b8c60943d8f99ec9965e',
    messagingSenderId: '322685866747',
    projectId: 'fluttertest-bee29',
    storageBucket: 'fluttertest-bee29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9CB7qidzPBUxVTyz_mx_jS6bVorXJ7Uo',
    appId: '1:322685866747:ios:b6eb0af367d77b5cc9965e',
    messagingSenderId: '322685866747',
    projectId: 'fluttertest-bee29',
    storageBucket: 'fluttertest-bee29.appspot.com',
    androidClientId: '322685866747-p4vgfp8j0265gugvjapbqoo6okg3fok3.apps.googleusercontent.com',
    iosClientId: '322685866747-mvrcmsrp6f84iorls1kdof19c1ac8heq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTestApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9CB7qidzPBUxVTyz_mx_jS6bVorXJ7Uo',
    appId: '1:322685866747:ios:b6eb0af367d77b5cc9965e',
    messagingSenderId: '322685866747',
    projectId: 'fluttertest-bee29',
    storageBucket: 'fluttertest-bee29.appspot.com',
    androidClientId: '322685866747-p4vgfp8j0265gugvjapbqoo6okg3fok3.apps.googleusercontent.com',
    iosClientId: '322685866747-mvrcmsrp6f84iorls1kdof19c1ac8heq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTestApplication',
  );
}
